title: The Coffee Archives
description: Speculative fiction and fine beverages.

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: Reviews
   url: /reviews

social:
   github: CoffeeArchives
   twitter: tctippens
   facebook: tctippens
   email: tctippens@gmail.com

google_analytics: "UA-58263416-1"
